### ISSUE TITLE
Add "Busy indicators" if they work

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#11]
http://blog.holoviz.org/panel_0.10.0.html#Busy-indicators

One day, it would be cool to have that! (not urgent)

**Comment by fmaussion** [comment]
Opened a report on panel: https://github.com/holoviz/panel/issues/1755

**Comment by pat-schmitt** [comment]
With the `pn.indicators.LoadingSpinner` the performance of the app is getting quite bad (around 1 min instead of 20 sec). But I think this would be cooler.
 
![loading_spinner_version_1](https://user-images.githubusercontent.com/50843444/103227859-b42bec00-492f-11eb-87f2-e00819f975a4.gif)


And here I have three versions with the `pn.indicators.BooleanStatus`. I think first version is the best but maybe there is a version four I have not considered.
Version 1:
![boolen_indicator_version_1](https://user-images.githubusercontent.com/50843444/103227950-efc6b600-492f-11eb-9ed2-c725b2e22423.gif)

Version 2:
![boolen_indicator_version_2](https://user-images.githubusercontent.com/50843444/103227976-0705a380-4930-11eb-8c72-d874e117d5bf.gif)

Version 3:
![boolen_indicator_version_3](https://user-images.githubusercontent.com/50843444/103227994-1389fc00-4930-11eb-90bd-ddb9a837618e.gif)

**Comment by fmaussion** [comment]
> With the pn.indicators.LoadingSpinner the performance of the app is getting quite bad (around 1 min instead of 20 sec)

This is horrible!!! It shouldn't change anything, and maybe something we should report to panel? Pinging @philippjfr in case he has time to answer...

From all version I prefer option 3, but to be honest I'm not sure the BooleanStatus indicator is really helping here...

**Comment by philippjfr** [comment]
That's pretty crazy. I'll try profiling the performance. One quick question I have though, have you tried using the new templates yet? They should be a quick win to make the app look more polished but should also result in significant performance improvements.

**Comment by fmaussion** [comment]
> One quick question I have though, have you tried using the new templates yet? 

I don't think we have... The app is pretty complex already (https://bokeh.oggm.org/simulator/app). but if you estimate that it's not going to be too much work we can have it a go. What do you think @pat-schmitt ?

**Comment by pat-schmitt** [comment]
Until now I have not looked at the templates in detail and how to use them, but I will in the next weeks.

> From all version I prefer option 3, but to be honest I'm not sure the BooleanStatus indicator is really helping here...

And yes I also think the BooleanStatus does not give more information than the inactive buttons.

**Comment by pat-schmitt** [comment]
I now implemented a template from panel for the app layout and included the Loadingspinner as shown in option 3. The layout has not changed but the performance with the Loadingspinner is now comparable with the version without it.

**Comment by philippjfr** [comment]
Great! Any idea what was causing the poor performance?

**Comment by pat-schmitt** [comment]
No, I have not been able to reproduce the poor performance. Now it is also working when no template is used.
My guess is that it might be related to an update of the browser, but that is just an amateurish guess.

**Comment by fmaussion** [comment]
Thanks @pat-schmitt ! I think the indicator makes the app better, as users are now seeing that something is happening. I think we should make a new release soon.

The big deal would be to have a stop button as discussed already with @philippjfr , but this is another story ;-)

**Comment by philippjfr** [comment]
For a stop button I'd probably recommend starting a thread and sending an event to that thread to cancel the operation.

**Comment by pat-schmitt** [comment]
Ok thanks, I will try again with a thread.
