### ISSUE TITLE
Add more safeguards to prevent long model runs

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#4]
By playing along yesterday I came on two ideas to stop a run when it becomes very unstable:

- we could add a wall-clock timer for each 10 years step that would stop the run if a 10 years step needs too long to run. For example:

```python

import signal

def _timeout_handler(signum, frame):
    raise TimeoutError('This run was killed because of timeout')

step_timeout = 10
signal.signal(signal.SIGALRM, _timeout_handler)

while (t_rate > 0.001) and (model.yr < max_calc_years) and (was_close_zero < 5):
        # Start the timer
        signal.alarm(step_timeout)
        model.run_until(model.yr + dyears)
        signal.alarm(0)
        
```

Or something similar.

- we could stop the simulation when the glacier grows out of the domain. I think that this solution would be enough and would make the complex one above obsolete.

@pat-schmitt , thoughts?

**Comment by pat-schmitt** [comment]
I think both ideas good, to circumvent the missing (and not easy to realize) stop functionality. 
- for the time dependent stop criterion i would make the stop time choose able (like the maximum simulation years), because it is dependent on how much years you are advance in each time step
- and also making the simulation stop when the glacier is out of the domain as an optional stop criterion. As default I would choose that the simulation will stopped, but maybe there will be some experiments where one want to switch this off

**Comment by pat-schmitt** [comment]
I just added the choosable ability that the model stops when the glacier is moving outside the domain. I think this is enough, and I will remark in the help text when this is switched off that a modal run can take quite a while.

**Comment by fmaussion** [comment]
Closing this!
