### ISSUE TITLE
Show model progress option affects the equilibrium condition

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#9]
I may understand why this happens, but we need to work around this problem -> the model behavior should be exact same regardless of the "show" step.

Furthermore, the "advance model" button also stops when "equilibrium" is reached. This also shouldn't happen!

**Comment by pat-schmitt** [comment]
Yes this is true, the equilibrium time should not depend on the step size. 
I have three ideas:
- run every possible experiment and save the equilibrium times (lots of computing and not very elegant)
- try to run the model to equilibrium in a second thread and hope to be faster in the equilibrium run (not easy programming wise and maybe also timing problems)
- let the model in the background always progress in one year steps to check for equilibrium and only show the progress according to the selected option (will slow down the computing time)

I think the third option is the best one. I can program it and then look how much longer a experiment will take. 

For 'advance model' I included this stop criterion, because i thought after the glacier reached equilibrium there is no change anymore and it is a information for the user that the glacier is in equilibrium. But I can easily let the glacier run the whole time, but I will keep the equilibrium information at the end. Or what do you think?

**Comment by fmaussion** [comment]
Thanks Patrick! 

The third is the correct option, and it shouldn't make it longer (internally the model forces landing on monthly steps anyway: 

https://github.com/OGGM/oggm/blob/b87ffdaa52e742f7d871a3ea2676a06d7c7e9a98/oggm/core/flowline.py#L817-L820

Note that checking equlibirum on 1 or 2 years step is not good, it creates "wrong equilibriums". So no matter the plotted time step, equilibrium should always be checked on 5 or 10 years steps. It probably means that the "plotting steps" should only be chosen from: 1, 2, 5, 10 and the equilibrium check should always be done on 10 years steps.

> But I can easily let the glacier run the whole time, but I will keep the equilibrium information at the end. Or what do you think?

Yes, I think that if people want to run the model for X time it should run for X time (path of least surprise). Furthermore, the "equilibrium" is not perfect, as shown above, i.e. the "run for X time" should be straight forward.
